### ISSUE TITLE
Configurable default date/time

### ISSUE THREAD

**Issue by Namnodorel** [vanpra/ComposeDateTimePicker#2]
In many use cases, the user has to select a date for something, and has the option to adjust the choice later. In such cases, it would be useful to be able to set a default date that the picker starts with, instead of always starting with the current date/time as a default.

**Comment by vanpra** [comment]
Thanks for the suggestion. I have implemented this and included an example in the documentation

**Comment by Namnodorel** [comment]
Thank you! :D I must say absolute respect for the response and change time, having someone who reacts this quickly is a rare quality.

**Comment by vanpra** [comment]
No problem. I'm pretty free at the moment so if you have any issues or want any new features create an issue and I'll try and get to it as soon as possible
